version: '3'

services:

  # caddy
  proxy:
    build:
      context: ./proxy
      args:
        - caddy_revision=${caddy_revision}

    environment:
      DOMAIN: asdas.net

    ports:
      - "80:8080"
      - "443:8443"
